### ISSUE TITLE
Your .jar contains Trojan:Script/Wacatac.B!ml trojan?

### ISSUE THREAD

**Issue by yermachello** [Crendgrim/SilentScreenshots#1]
Windows Defender deletes the file as soon as it's downloaded, why is it so? :)

**Comment by Crendgrim** [comment]
I have no idea. Windows Defender is notorious for detecting false positives.

You should always download my mods from CurseForge or Modrinth. If the archive was actually compromised, those sites would have caught it as well. If you're downloading it from somewhere else, get it from one of those. If it comes from there, blame Windows Defender.
